name: Day 7 Manual Run

on:
  workflow_dispatch:

jobs:
  run-day7:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          env:
          SHEETY_API_GET: ${{ secrets.SHEETY_API_GET }}
          FLIGHT_KEY: ${{ secrets.FLIGHT_KEY }}
          FLIGHT_GET_URL: ${{ secrets.FLIGHT_GET_URL }}
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
          MY_NUMBER: ${{ secrets.MY_NUMBER }}
        run: |
          cd "Day 6-Cheap Flight SMS"
          python main.py
