name: Stock News Bot

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      STOCK_API_KEY: ${{ secrets.STOCK_API_KEY }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests twilio

      - name: Run script
        working-directory: Day 4-TSLA Stock Tracker
        run: python main.py
